### ISSUE TITLE
Labels in LaTeX snippets

### ISSUE THREAD

**Issue by beojan** [hlissner/doom-snippets#33]
Can you add a `%` at the end of the line preceding labels so chktex doesn't complain about potentially getting page numbers wrong?

**Comment by hlissner** [comment]
Could you expand on what the problem is here? Why would `%` fix this? Why does the lack of it cause chktex to complain about page numbers?

Are you talking about a literal `%` (perhaps some syntax I'm not aware of) or our alias for `yas-selected-text`? Could you be more specific about where `the end of the line preceding labels` means?

Since you're mention "latex snippets" and labels, are you talking about https://github.com/hlissner/doom-snippets/blob/master/latex-mode/label? Or "labels" generally?

**Comment by beojan** [comment]
It comments out the linebreak after `\section` or `\subsection` so the `\label` is on the same (logical) line.

Chktex complains because it's theoretically possible that the heading is the last line on a page, and the page number corresponding to the label won't be the same as that corresponding to the heading.
