### ISSUE TITLE
Editing or disabling some of the predefined snippets

### ISSUE THREAD

**Issue by roiholtzman** [hlissner/doom-snippets#64]
Sorry for the elementary question.
I am trying to disable of edit one of the `latex-mode` snippets.
I am running `yas-visit-snippet-file`, and go to the wanted file (in my case it is the `frame` snippet). Then I try to edit it but I guess I can't because this snippet is locked. How can I still edit it or override it?

I have defined another snippet with the same key (`fr`) but now when I type `fr TAB` I need to choose which snippet I want to use which costs me an extra key. I would like it to insert my new snippet.

**Comment by hlissner** [comment]
If you are using [Doom Emacs](https://github.com/hlissner/doom-emacs) you can add a snippet to `~/.doom.d/snippets/latex-mode/fr` and it will shadow the default one (so long as it has the same `name` or `uuid`).

If you don't use Doom Emacs, you'll need to either:

1. Clone doom-snippets somewhere local and modify it in place.
2. Or do as Doom did to allow for shadowing:
   a. Add a private snippets directory to `yas-snippet-dirs`
   b. And [add a function to `yas-prompt-functions`](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/snippets/config.el#L59) that will [prioritize snippets in your private directory over ones in `doom-snippets`](https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/snippets/autoload/snippets.el#L8-L28)

Since this isn't an actionable issue I'll close this, but feel free to follow up here.
